name: My First CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello JumpToTech CI"

      - name: Test Failure
        run: exit 1

      - name: Finish
        run: echo "CI PASSED"
