name: My First CI

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Say hello
        run: echo "Hello JumpToTech CI"

      - name: Check index.html exists
        run: test -f index.html

      - name: Finish
        run: echo "CI PASSED"
