name: My First CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello JumpToTech CI"

      - name: Check files
        run: ls -la

      - name: CI completed
        run: echo "CI PASSED"
